set nocompatible
filetype plugin on

syntax on           "Always enable syntax highlighting
set number          "display line numbers
set laststatus=2    "Always display a statusline for windows

"Indention and tabs/space autoformatting
set ai              "autoindent
set si              "smartindent
set tabstop=4       "tabsize
set shiftwidth=4    "indentsize
set expandtab       "tabs to space
set softtabstop=4   "treat 4 spaces like a tab

"Change and scrolling behavior
set autoread        "reload on change from outside
set so=5            "keep lines above/below the cursor

set hls             "highlight matching search patterns

"Colors
colorscheme desert
"Highlight characters after column 80
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/

map Y y$            "yank to the end of the current line
